"""Generate the surrounding ROS 2 ament_cmake package files for a URDF."""

from __future__ import annotations

import re
from pathlib import Path

ROS_PACKAGE_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_package_name(name: str) -> None:
    """Raise ValueError if *name* is not a valid ROS package name.

    Valid names start with a lowercase letter, then contain only lowercase
    alphanumeric characters or underscores (no hyphens, no uppercase, no
    leading digits).
    """
    if not ROS_PACKAGE_NAME_RE.match(name):
        raise ValueError(
            f"invalid ROS package name {name!r}: must match "
            f"{ROS_PACKAGE_NAME_RE.pattern} "
            "(start with lowercase letter, then lowercase alphanumeric or underscore)"
        )


def _validate_urdf_relpath(p: Path) -> None:
    """Raise ValueError if *p* is absolute or contains '..' path segments."""
    if p.is_absolute():
        raise ValueError(f"urdf_relpath must be relative, got absolute path {p}")
    if ".." in p.parts:
        raise ValueError(f"urdf_relpath must not contain '..' segments, got {p}")


PACKAGE_XML = """\
<?xml version="1.0"?>
<package format="3">
  <name>{package_name}</name>
  <version>0.0.1</version>
  <description>URDF package generated by cad2urdf.</description>
  <maintainer email="{maintainer_email}">{maintainer_name}</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""

CMAKELISTS = """\
cmake_minimum_required(VERSION 3.8)
project({package_name})

find_package(ament_cmake REQUIRED)

install(DIRECTORY urdf meshes launch rviz
  DESTINATION share/${{PROJECT_NAME}}
)

ament_package()
"""

LAUNCH_PY = """\
from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.substitutions import Command
from launch_ros.actions import Node


def generate_launch_description():
    pkg_share = Path(get_package_share_directory("{package_name}"))
    urdf_path = pkg_share / "{urdf_relpath}"
    rviz_path = pkg_share / "rviz" / "display.rviz"

    robot_description = Command(["xacro ", str(urdf_path)])

    return LaunchDescription([
        Node(
            package="robot_state_publisher",
            executable="robot_state_publisher",
            parameters=[{{"robot_description": robot_description}}],
        ),
        Node(
            package="joint_state_publisher_gui",
            executable="joint_state_publisher_gui",
        ),
        Node(
            package="rviz2",
            executable="rviz2",
            arguments=["-d", str(rviz_path)],
        ),
    ])
"""

RVIZ_CONFIG = """\
Panels:
  - Class: rviz_common/Displays
    Name: Displays
Visualization Manager:
  Class: ""
  Displays:
    - Class: rviz_default_plugins/Grid
      Enabled: true
      Name: Grid
    - Class: rviz_default_plugins/RobotModel
      Enabled: true
      Name: RobotModel
      Description Topic:
        Value: /robot_description
  Global Options:
    Fixed Frame: {base_link_name}
"""


def scaffold_ros_package(
    *,
    out_dir: Path,
    package_name: str,
    urdf_relpath: Path,
    maintainer_name: str,
    maintainer_email: str,
    base_link_name: str = "base",
) -> None:
    """Create a ROS 2 ament_cmake package skeleton at `out_dir`.

    Creates: package.xml, CMakeLists.txt, launch/display.launch.py, rviz/display.rviz,
    plus empty urdf/ and meshes/{visual,collision}/ directories the URDF emitter
    will populate.

    Args:
        out_dir: Destination directory (created if absent).
        package_name: ROS package name — must satisfy ``[a-z][a-z0-9_]*``.
        urdf_relpath: Path to the URDF inside the package (must be relative,
            no ``..`` segments).
        maintainer_name: Author name for package.xml.
        maintainer_email: Author e-mail for package.xml.
        base_link_name: Name of the fixed frame used in the RViz config
            (default: ``"base"``).
    """
    _validate_package_name(package_name)
    _validate_urdf_relpath(urdf_relpath)

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "urdf").mkdir(exist_ok=True)
    (out_dir / "meshes" / "visual").mkdir(parents=True, exist_ok=True)
    (out_dir / "meshes" / "collision").mkdir(parents=True, exist_ok=True)
    (out_dir / "launch").mkdir(exist_ok=True)
    (out_dir / "rviz").mkdir(exist_ok=True)

    (out_dir / "package.xml").write_text(
        PACKAGE_XML.format(
            package_name=package_name,
            maintainer_name=maintainer_name,
            maintainer_email=maintainer_email,
        )
    )
    (out_dir / "CMakeLists.txt").write_text(CMAKELISTS.format(package_name=package_name))
    (out_dir / "launch" / "display.launch.py").write_text(
        LAUNCH_PY.format(package_name=package_name, urdf_relpath=urdf_relpath.as_posix())
    )
    (out_dir / "rviz" / "display.rviz").write_text(
        RVIZ_CONFIG.format(base_link_name=base_link_name)
    )
